name: Mondoo AWS Account Scan
on:
  workflow_run:
    workflows: ["Terraform Test", "Terraform Security Scan"]
    types:
      - completed

jobs:
  security-scan-aws-account:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
    steps:
    - uses: mondoohq/actions/aws@scottford/refactor-actions
      with:
        service-account-credentials: ${{ secrets.MONDOO_SERVICE_ACCOUNT }}
        output: compact
        score-threshold: 0