name: Terraform Test
on: push

jobs:
  terraform-ci-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true