name: Mondoo Terraform Security Static Analysis
on:
  workflow_run:
    workflows: ["Terraform CI"]
    types:
      - completed

jobs:
  mondoo-scan-terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: mondoohq/actions/terraform@scottford/refactor-actions
      with:
        service-account-credentials: ${{ secrets.MONDOO_SERVICE_ACCOUNT }}
        path: terraform