name: Terraform Security Scan
on:
  workflow_run:
    workflows: ["Terraform Test"]
    types:
      - completed

jobs:
  terraform-ci-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: mondoohq/actions/terraform@scottford/refactor-actions
      with:
        service-account-credentials: ${{ secrets.MONDOO_SERVICE_ACCOUNT }}
        path: terraform